//*Archivo creado para simular data con la que se trabajara en la home

const allDonations = [{
    "id": 1,
    "fechaDonacion": "8/1/2023",
    "monto": 54,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 2,
    "fechaDonacion": "12/22/2022",
    "monto": 11,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 3,
    "fechaDonacion": "9/24/2022",
    "monto": 23,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 4,
    "fechaDonacion": "7/18/2023",
    "monto": 88,
    "estadoDonacion": 'rechazado'
  }, {
    "id": 5,
    "fechaDonacion": "9/2/2022",
    "monto": 93,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 6,
    "fechaDonacion": "12/8/2022",
    "monto": 33,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 7,
    "fechaDonacion": "11/23/2022",
    "monto": 23,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 8,
    "fechaDonacion": "12/3/2022",
    "monto": 2,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 9,
    "fechaDonacion": "7/18/2023",
    "monto": 7,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 10,
    "fechaDonacion": "12/18/2022",
    "monto": 35,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 11,
    "fechaDonacion": "3/16/2023",
    "monto": 69,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 12,
    "fechaDonacion": "11/11/2022",
    "monto": 79,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 13,
    "fechaDonacion": "4/13/2023",
    "monto": 42,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 14,
    "fechaDonacion": "3/29/2023",
    "monto": 66,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 15,
    "fechaDonacion": "7/22/2023",
    "monto": 89,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 16,
    "fechaDonacion": "8/30/2022",
    "monto": 81,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 17,
    "fechaDonacion": "6/13/2023",
    "monto": 95,
    "estadoDonacion": 'aprobado'
  }, {
    "id": 18,
    "fechaDonacion": "6/10/2023",
    "monto": 42,
    "estadoDonacion": 'rechazado'
  }, {
    "id": 19,
    "fechaDonacion": "1/11/2023",
    "monto": 90,
    "estadoDonacion": 'pendiente'
  }, {
    "id": 20,
    "fechaDonacion": "6/2/2023",
    "monto": 85,
    "estadoDonacion": 'aprobado'
  }]

  module.exports = allDonations